version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinic-mohammadi-backend
    restart: unless-stopped
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=dental_clinic.settings
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - clinic-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: clinic-mohammadi-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - clinic-network

volumes:
  static_volume:
  media_volume:

networks:
  clinic-network:
    driver: bridge 