# Generated by Django 5.2.4 on 2025-08-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام خدمات')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('composite', 'کامپوزیت'), ('cosmetic', 'زیبایی'), ('preventive', 'پیشگیری'), ('emergency', 'اورژانس'), ('consultation', 'مشاوره')], max_length=50, verbose_name='دسته بندی')),
                ('duration', models.IntegerField(help_text='مدت زمان به دقیقه', verbose_name='مدت زمان')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'ویژگی خدمات',
                'verbose_name_plural': 'ویژگی های خدمات',
            },
        ),
    ]
