# Generated by Django 5.2.4 on 2025-08-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '__first__'),
        ('patients', '0001_initial'),
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاریخ نوبت')),
                ('appointment_time', models.TimeField(verbose_name='ساعت نوبت')),
                ('appointment_type', models.CharField(choices=[('consultation', 'مشاوره'), ('composite_filling', 'پر کردن کامپوزیت'), ('composite_veneer', 'ونیر کامپوزیت'), ('composite_bonding', 'باندینگ کامپوزیت'), ('teeth_whitening', 'سفید کردن دندان'), ('dental_cleaning', 'جرم گیری'), ('emergency', 'اورژانس')], max_length=50, verbose_name='نوع نوبت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='دکتر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='بیمار')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
