# Generated by Django 5.2.4 on 2025-08-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس اضطراری')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='سابقه پزشکی')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='آلرژی\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوای یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'یادداشت بیمار',
                'verbose_name_plural': 'یادداشت\u200cهای بیمار',
                'ordering': ['-created_at'],
            },
        ),
    ]
