# Generated by Django 5.2.4 on 2025-08-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام کامل')),
                ('specialization', models.CharField(choices=[('composite_dentistry', 'کامپوزیت دندان'), ('cosmetic_dentistry', 'زیبایی دندان'), ('general_dentistry', 'دندانپزشکی عمومی'), ('orthodontics', 'ارتودنسی'), ('endodontics', 'اندودنتیکس'), ('periodontics', 'پریودنتیکس')], max_length=50, verbose_name='تخصص')),
                ('education', models.TextField(verbose_name='تحصیلات')),
                ('experience_years', models.IntegerField(verbose_name='سال\u200cهای تجربه')),
                ('bio', models.TextField(verbose_name='بیوگرافی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='تصویر')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکترها',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنج\u200cشنبه'), ('friday', 'جمعه'), ('saturday', 'شنبه'), ('sunday', 'یکشنبه')], max_length=20, verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='دکتر')),
            ],
            options={
                'verbose_name': 'برنامه کاری',
                'verbose_name_plural': 'برنامه\u200cهای کاری',
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
